### ISSUE TITLE
Edit Subscription Plan of Users from superadmin panel

### ISSUE THREAD

**Issue by shubhammishra49** [uilibrary/Linkdrop-Feature-And-Issues#6]
please add option to edit subscription plan from super admin panel.

**Comment by jamir-hossain** [comment]
Already subscription plan edit options are included. Please log in as a super admin first. Then go to the admin panel, Here you will find "Pricing Plan" route. Click this route then you find the list of the created subscription list. Now you can create or update the pricing plan.
