### ISSUE TITLE
Social Signals not been added to bio page

### ISSUE THREAD

**Issue by stan8837** [uilibrary/Linkdrop-Feature-And-Issues#7]
The social media signals are not been added to the users bio page, this issue has been requested over and over again but its not been fixed

![Screenshot_53](https://github.com/uilibrary/Linkdrop-Feature-And-Issues/assets/83278147/2de233c7-a69a-45ba-839f-e2d2a928b732)

**Comment by jamir-hossain** [comment]
It has been fixed. If you update your app to the latest version then I hope you will not face this issue.
